import Head from 'next/head';


import Contact from '../components/Contact';
import About from '../components/About';
import CareersSection from '../components/Careersection';
import Aos from "aos";
import "aos/dist/aos.css";
import React, {useEffect } from 'react';
import Solutions from '../components/Solutions';



export default function Home() {

  useEffect(() =>{
    Aos.init({duration:2500,
  });
  },[]);

  return (
   
    <div className="">
      <Head>
        <title>Finik Technology</title>
        <meta name='description' content='Generated by create next app' />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel='icon' href='/logo.ico' />
      </Head>
        
          
              <div data-aos="zoom-out" >
              {/* <Hero message="Delivering the best solutions with cutting-edge technologies" /> */}

              <main className="flex z-20 items-center bg-black bg-opacity-50 justify-center h-screen p-24">
            <video
                autoPlay
                loop
                muted
                className="absolute -z-10 h-screen w-screen object-cover blur-sm"
            >
               <source src="hero.mp4" type="video/mp4" />Your browser does not support the video tag.
            </video>
            <div className="max-w-7xl mx-auto flex justify-between  bg-opacity-90 p-3 rounded-lg ">
            
            <div className="w-full md:w-1/2 space-y-6 p-4"></div>
            <div cl></div>
            <div className="w-full md:w-1/2 space-y-6 dark:bg-black dark:bg-opacity-50 bg-white bg-opacity-80 p-4 rounded-lg">
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold tracking-tigh dark:text-white text-black ">
            Join us on a journey to explore the limitless possibilities
          </h1>
          <p className="text-lg sm:text-xl lg:text-2xl dark:text-white text-black">
          empower businesses and individuals with cutting-edge technology solutions that drive success and transformation
          </p>
          </div>
          <div>

          </div>
          </div>
        </main>
              </div>
              <About />
              <div><Solutions /></div>
              <div data-aos="zoom-out">
              <CareersSection></CareersSection>
              </div>
          
              <div data-aos="zoom-out" >
              <Contact />
         
              </div>
           
 
      
        

        
      
    </div>

  );
}
