import Head from 'next/head';


import Contact from '../components/Contact';
import About from '../components/About';
import CareersSection from '../components/Careersection';
import Aos from "aos";
import "aos/dist/aos.css";
import React, {useEffect, useState } from 'react';
import Solutions from '../components/Solutions';



export default function Home() {

  const [currentIndex, setCurrentIndex] = useState(0);

  const statements = [
    "Join us on a journey to explore the limitless possibilities",
    "We help you build your future.",
    "Let's create something amazing together."
  ];

  const substatements = [
    "empower businesses and individuals with cutting-edge technology solutions that drive success and transformation",
    "With a team of visionary experts and a commitment to excellence, we deliver customized, high-performance solutions tailored to meet your unique needs.",
    "We are dedicated to providing unparalleled service and delivering IT solutions that empower our clients to achieve their goals. Your success is our success, and together, we can create a future filled with possibilities."
  ]

  useEffect(() =>{
    Aos.init({duration:2500,
  });
  },[])

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentIndex((prevIndex) => (prevIndex + 1) % statements.length);
    }, 5000);

    return () => clearInterval(interval);
  }, []);



  return (
   
    <div className="">
<Head>
        <title>Finik Technology</title>
        <meta name='description' content='Generated by create next app' />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel='icon' href='/logo.ico' />
</Head>
        
          
              <div data-aos="zoom-out" >
      

              <main className="flex z-20 items-center bg-black bg-opacity-50 justify-center h-screen p-24">
            <video
                autoPlay
                loop
                muted
                className="absolute -z-10 h-screen w-screen object-cover blur-sm"
            >
               <source src="hero.mp4" type="video/mp4" />Your browser does not support the video tag.
            </video>
            <div className="max-w-7xl mx-auto flex justify-between  bg-opacity-90 p-3 rounded-lg ">
            
            <div className="w-full md:w-1/2 space-y-6 p-4"></div>
            <div cl></div>
            <div className="w-full md:w-1/2 space-y-6 dark:bg-black dark:bg-opacity-50 bg-white bg-opacity-80 p-4  rounded-lg " key={currentIndex}>
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold tracking-tigh dark:text-white text-black transition-opacity duration-1000 ease-in-out" key={currentIndex}>
            {statements[currentIndex]}
          </h1>
          <p className="text-lg sm:text-xl lg:text-2xl dark:text-white text-black transition-opacity duration-2000 ease-in-out" key={currentIndex}>
          {substatements[currentIndex]}
          </p>
          <div className="flex justify-center items-center space-x-2">
          {statements.map((_, index) => (
            <span
              key={index}
              className={`w-3 h-3 rounded-full cursor-pointer ${
                currentIndex === index ? "bg-white" : "bg-gray-400"
              }`}
              onClick={() => setCurrentIndex(index)}
            ></span>
          ))}
        </div>
          </div>
          
          <div>

          </div>
          </div>
        </main>
              </div>
              <About />
              <div><Solutions /></div>
              <div data-aos="zoom-out">
              <CareersSection></CareersSection>
              </div>
          
              <div data-aos="zoom-out" >
              <Contact />
         
              </div>
           
 
      
        

        
      
    </div>

  );
}
